CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email varchar(255) UNIQUE NOT NULL,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    available boolean NOT NULL,
    owner_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE NOT NULL,
    booker_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    status varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text varchar(255) NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

