CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email varchar UNIQUE NOT NULL,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar NOT NULL,
    available boolean NOT NULL,
    owner_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE NOT NULL,
    booker_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    status varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text varchar NOT NULL,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE NOT NULL,
    author_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
)

